<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <RootNamespace>TempSim.Core</RootNamespace>
    <Version>2.0.1</Version>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
</Project>
