/* generated by dbc2tables.py from tempctl.dbc - do not edit */
#pragma once

/* TempCtl: j1939_bam, 27 signals: Setpoint, DeadbandHi, DeadbandLo, HiLimit, LoLimit, ErrorTimeoutMs, DeadbandTimeoutMs, FilterPoints, Temp2Enable, Temp2Tolerance, FeedbackEnable, Temp1, Temp2, HeaterFeedback, CoolerFeedback, HeatingCmd, CoolingCmd, ErrorStatus, TempStatus, ControlTemp, Temp1Filtered, Temp2Filtered, HiBand, LoBand, ErrorRemainMs, DbRemainMs, ActiveSensor */
static const double TempCtl_msgdef[8] = { 419365118.0, 1.0, 50.0, 1.0, -1.0, 255.0, 255.0, 1000.0 };
static const double TempCtl_sigdefs[27][8] = {
    { 0.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Setpoint */
    { 16.0, 16.0, 0.0, 0.0, 0.03125, 0.0, 0.0, 2007.96875 }, /* DeadbandHi */
    { 32.0, 16.0, 0.0, 0.0, 0.03125, 0.0, 0.0, 2007.96875 }, /* DeadbandLo */
    { 48.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* HiLimit */
    { 64.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* LoLimit */
    { 80.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* ErrorTimeoutMs */
    { 112.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* DeadbandTimeoutMs */
    { 144.0, 8.0, 0.0, 0.0, 1.0, 0.0, 1.0, 64.0 }, /* FilterPoints */
    { 152.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* Temp2Enable */
    { 160.0, 16.0, 0.0, 0.0, 0.03125, 0.0, 0.0, 2007.96875 }, /* Temp2Tolerance */
    { 176.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* FeedbackEnable */
    { 184.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp1 */
    { 200.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp2 */
    { 216.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* HeaterFeedback */
    { 218.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* CoolerFeedback */
    { 220.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* HeatingCmd */
    { 222.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* CoolingCmd */
    { 224.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1023.0 }, /* ErrorStatus */
    { 240.0, 4.0, 0.0, 0.0, 1.0, 0.0, 0.0, 8.0 }, /* TempStatus */
    { 248.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* ControlTemp */
    { 264.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp1Filtered */
    { 280.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp2Filtered */
    { 296.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* HiBand */
    { 312.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* LoBand */
    { 328.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* ErrorRemainMs */
    { 360.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* DbRemainMs */
    { 392.0, 2.0, 0.0, 0.0, 1.0, 0.0, 1.0, 2.0 }, /* ActiveSensor */
};
#define TempCtl_NSIG 27

