/* generated by dbc2tables.py from tempctl.dbc - do not edit */
#pragma once

/* TempCtl: j1939_bam, 25 signals: ControlTemp, ActiveSensor, Temp1Raw, Temp2Raw, Temp2Corrected, Temp1Avg, Temp2Avg, HiBand, LoBand, InitialHcFlag, DeadbandRemainMs, AtSetPtRemainMs, CompareRemainMs, HeaterFbRemainMs, CoolerFbRemainMs, Temp1OorAccumMs, Temp2OorAccumMs, Temp1OorEventsPerHour, Temp2OorEventsPerHour, Status, Warning, DoHeater, DoCooler, AppliedFilterPoints, ZoneInitialized */
static const double TempCtl_msgdef[8] = { 419365118.0, 1.0, 55.0, 1.0, -1.0, 255.0, 255.0, 1000.0 };
static const double TempCtl_sigdefs[25][8] = {
    { 0.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* ControlTemp */
    { 16.0, 4.0, 0.0, 0.0, 1.0, 0.0, 1.0, 2.0 }, /* ActiveSensor */
    { 24.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp1Raw */
    { 40.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp2Raw */
    { 56.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp2Corrected */
    { 72.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp1Avg */
    { 88.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp2Avg */
    { 104.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* HiBand */
    { 120.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* LoBand */
    { 136.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* InitialHcFlag */
    { 144.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* DeadbandRemainMs */
    { 176.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* AtSetPtRemainMs */
    { 208.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* CompareRemainMs */
    { 240.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* HeaterFbRemainMs */
    { 272.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* CoolerFbRemainMs */
    { 304.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* Temp1OorAccumMs */
    { 336.0, 32.0, 0.0, 0.0, 1.0, 0.0, 0.0, 4211081215.0 }, /* Temp2OorAccumMs */
    { 368.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64254.0 }, /* Temp1OorEventsPerHour */
    { 384.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64254.0 }, /* Temp2OorEventsPerHour */
    { 400.0, 8.0, 0.0, 0.0, 1.0, 0.0, 0.0, 250.0 }, /* Status */
    { 408.0, 8.0, 0.0, 0.0, 1.0, 0.0, 0.0, 250.0 }, /* Warning */
    { 416.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* DoHeater */
    { 418.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* DoCooler */
    { 424.0, 8.0, 0.0, 0.0, 1.0, 0.0, 1.0, 64.0 }, /* AppliedFilterPoints */
    { 432.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* ZoneInitialized */
};
#define TempCtl_NSIG 25

