/* generated by dbc2tables.py from tempctl.dbc - do not edit */
#pragma once

/* TempCtl: j1939_bam, 28 signals: ControlTemp, ActiveSensor, Temp1Raw, Temp2Raw, Temp2Corrected, Temp1Avg, Temp2Avg, HiBand, LoBand, InitialHcFlag, DeadbandRemainMs, AtSetPtRemainMs, CompareRemainMs, HeaterFbRemainMs, CoolerFbRemainMs, Temp1OorAccumMs, Temp2OorAccumMs, Temp1OorEventsPerHour, Temp2OorEventsPerHour, Status, Warning, DoHeater, DoCooler, AppliedFilterPoints, ZoneInitialized, RunPermissive, OperatingConditionRemainMs, ControllerStarted */
static const double TempCtl_msgdef[8] = { 419365118.0, 1.0, 44.0, 1.0, -1.0, 255.0, 255.0, 1000.0 };
static const double TempCtl_sigdefs[28][8] = {
    { 0.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* ControlTemp */
    { 16.0, 4.0, 0.0, 0.0, 1.0, 0.0, 1.0, 2.0 }, /* ActiveSensor */
    { 24.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp1Raw */
    { 40.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp2Raw */
    { 56.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp2Corrected */
    { 72.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp1Avg */
    { 88.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* Temp2Avg */
    { 104.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* HiBand */
    { 120.0, 16.0, 0.0, 0.0, 0.03125, -273.0, -273.0, 1734.96875 }, /* LoBand */
    { 136.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* InitialHcFlag */
    { 144.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64255.0 }, /* DeadbandRemainMs */
    { 160.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64255.0 }, /* AtSetPtRemainMs */
    { 176.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64255.0 }, /* CompareRemainMs */
    { 192.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64255.0 }, /* HeaterFbRemainMs */
    { 208.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64255.0 }, /* CoolerFbRemainMs */
    { 224.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64255.0 }, /* Temp1OorAccumMs */
    { 240.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64255.0 }, /* Temp2OorAccumMs */
    { 256.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64254.0 }, /* Temp1OorEventsPerHour */
    { 272.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64254.0 }, /* Temp2OorEventsPerHour */
    { 288.0, 8.0, 0.0, 0.0, 1.0, 0.0, 0.0, 250.0 }, /* Status */
    { 296.0, 8.0, 0.0, 0.0, 1.0, 0.0, 0.0, 250.0 }, /* Warning */
    { 304.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* DoHeater */
    { 306.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* DoCooler */
    { 312.0, 8.0, 0.0, 0.0, 1.0, 0.0, 1.0, 64.0 }, /* AppliedFilterPoints */
    { 320.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* ZoneInitialized */
    { 322.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* RunPermissive */
    { 328.0, 16.0, 0.0, 0.0, 1.0, 0.0, 0.0, 64255.0 }, /* OperatingConditionRemainMs */
    { 344.0, 2.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0 }, /* ControllerStarted */
};
#define TempCtl_NSIG 28

