# Generates DEPENDENCIES.txt (PE import tables of the DLLs/exes, ELF report of
# the .so) and MANIFEST.txt (file list with SHA-256) inside a staged
# distribution folder. Called by package_dist.bat.
param(
    [Parameter(Mandatory = $true)][string]$PackageDir,
    [Parameter(Mandatory = $true)][string]$Version,
    [string]$Password = 'scott',
    [string]$ElfInfoScript = ''
)

$ErrorActionPreference = 'Stop'

function Get-PeImports {
    param([string]$Path)
    $b = [System.IO.File]::ReadAllBytes($Path)
    $peOff = [BitConverter]::ToInt32($b, 0x3C)
    if ([BitConverter]::ToUInt32($b, $peOff) -ne 0x4550) { throw "$Path is not a PE file" }
    $machine = [BitConverter]::ToUInt16($b, $peOff + 4)
    $numSections = [BitConverter]::ToUInt16($b, $peOff + 6)
    $optSize = [BitConverter]::ToUInt16($b, $peOff + 20)
    $optOff = $peOff + 24
    $magic = [BitConverter]::ToUInt16($b, $optOff)
    $dirOff = $optOff + $(if ($magic -eq 0x20B) { 112 } else { 96 })
    $importRva = [BitConverter]::ToUInt32($b, $dirOff + 8)
    $sections = @()
    $secOff = $optOff + $optSize
    for ($i = 0; $i -lt $numSections; $i++) {
        $o = $secOff + $i * 40
        $sections += [pscustomobject]@{
            VirtualAddress = [BitConverter]::ToUInt32($b, $o + 12)
            SizeOfRawData  = [BitConverter]::ToUInt32($b, $o + 16)
            PointerToRaw   = [BitConverter]::ToUInt32($b, $o + 20)
        }
    }
    function RvaToOff([uint32]$rva) {
        foreach ($s in $sections) {
            if ($rva -ge $s.VirtualAddress -and $rva -lt ($s.VirtualAddress + $s.SizeOfRawData)) {
                return $s.PointerToRaw + ($rva - $s.VirtualAddress)
            }
        }
        throw "RVA 0x$($rva.ToString('X')) not mapped"
    }
    $imports = @()
    if ($importRva -ne 0) {
        $desc = RvaToOff $importRva
        while ($true) {
            $nameRva = [BitConverter]::ToUInt32($b, $desc + 12)
            if ($nameRva -eq 0) { break }
            $nOff = RvaToOff $nameRva
            $end = $nOff
            while ($b[$end] -ne 0) { $end++ }
            $imports += [System.Text.Encoding]::ASCII.GetString($b, $nOff, $end - $nOff)
            $desc += 20
        }
    }
    [pscustomobject]@{
        Machine = if ($machine -eq 0x8664) { 'x64' } elseif ($machine -eq 0x14C) { 'x86' } else { "0x$($machine.ToString('X'))" }
        Imports = $imports
    }
}

$lines = @("tempctl v$Version dependency report (generated at package time)", '')
$bad = $false
foreach ($rel in @('tempctl.dll', 'x86\tempctl.dll', 'test_tempctl.exe', 'x86\test_tempctl.exe')) {
    $p = Join-Path $PackageDir $rel
    if (-not (Test-Path -LiteralPath $p)) { continue }
    $info = Get-PeImports $p
    $lines += "$rel  [$($info.Machine)]"
    foreach ($imp in $info.Imports) { $lines += "  imports $imp" }
    $vcDeps = $info.Imports | Where-Object { $_ -match '(?i)vcruntime|msvcp|api-ms-win-crt|msvcr' }
    if ($vcDeps) {
        $lines += "  *** UNEXPECTED VC RUNTIME DEPENDENCY: $($vcDeps -join ', ') ***"
        $bad = $true
    } else {
        $lines += '  -> operating-system DLLs only; no VC++ runtime'
    }
    $lines += ''
}

# ELF report for the Linux artefacts (tools\elfinfo.py, needs python on PATH)
foreach ($rel in @('linux-x64\libtempctl.so', 'linux-x64\test_tempctl')) {
    $p = Join-Path $PackageDir $rel
    if (-not (Test-Path -LiteralPath $p)) { continue }
    $lines += "$rel  [ELF]"
    $py = Get-Command python -ErrorAction SilentlyContinue
    if ($ElfInfoScript -and $py -and (Test-Path -LiteralPath $ElfInfoScript)) {
        $out = & $py.Source $ElfInfoScript $p 2>&1
        foreach ($l in $out) { $lines += "  $l" }
        $needed = ($out | Where-Object { $_ -like 'NEEDED*' }) -join ' '
        if ($needed -match 'libstdc|libgcc_s|libm\.') {
            $lines += "  *** UNEXPECTED SHARED-LIBRARY DEPENDENCY: $needed ***"
            $bad = $true
        } else {
            $lines += '  -> libc only'
        }
    } else {
        $lines += '  (python / tools\elfinfo.py not available; ELF report skipped)'
    }
    $lines += ''
}
Set-Content -LiteralPath (Join-Path $PackageDir 'DEPENDENCIES.txt') -Value $lines -Encoding utf8
if ($bad) { Write-Host 'ERROR: unexpected runtime dependency found.'; exit 1 }

$manifest = @(
    "tempctl distribution package v$Version",
    'Generated by package_dist.bat',
    '',
    "Encrypted zip password: $Password",
    '',
    'Files (SHA-256):'
)
Get-ChildItem -LiteralPath $PackageDir -Recurse -File |
    Where-Object { $_.Name -ne 'MANIFEST.txt' } |
    Sort-Object { $_.FullName } |
    ForEach-Object {
        $rel = $_.FullName.Substring($PackageDir.Length).TrimStart('\')
        $hash = (Get-FileHash -LiteralPath $_.FullName -Algorithm SHA256).Hash
        $manifest += ('  {0,-40} {1}' -f $rel, $hash)
    }
Set-Content -LiteralPath (Join-Path $PackageDir 'MANIFEST.txt') -Value $manifest -Encoding utf8
Write-Host 'DEPENDENCIES.txt and MANIFEST.txt written.'
exit 0
